var nodes7 = require("nodes7");
var conn_plc = new nodes7(); //PLC1
var conn_plc_s2 = new nodes7(); //PLC2

// nodes7 tags Format:
var tags_list = {
  btt_Auto: "DB1,X0.0",
  btt_Manu: "DB1,X0.1",
  btt_Auto_Confirm: "DB1,X0.2",
  btt_V1_Open: "DB1,X0.3",
  btt_V1_Close: "DB1,X0.4",
  btt_V2_Open: "DB1,X0.5",
  btt_V2_Close: "DB1,X0.6",
  btt_V3_Open: "DB1,X0.7",
  btt_V3_Close: "DB1,X1.0",
  btt_DC_Tron_Run: "DB1,X1.1",
  btt_DC_Tron_Stop: "DB1,X1.2",
  btt_DC_Export_Run: "DB1,X1.3",
  btt_DC_Export_Stop: "DB1,X1.4",
  CB_Can: "DB1,X1.5",
  Q_Lamp_Auto: "DB1,X1.6",
  Q_Lamp_Manu: "DB1,X1.7",
  status_Valve_1: "DB1,BYTE2",
  status_Valve_2: "DB1,BYTE3",
  status_Valve_3: "DB1,BYTE4",
  status_DC_Tron: "DB1,BYTE5",
  status_DC_Export: "DB1,BYTE6",
  Setting_Time_Tron: "DB1,INT8",
  Act_Time_Tron: "DB1,INT10",
  Setting_Weight_1: "DB1,REAL12",
  Setting_Weight_2: "DB1,REAL16",
  Setting_Weight_3: "DB1,REAL20",
  Act_Weight_1: "DB1,REAL24",
  Act_Weight_2: "DB1,REAL28",
  Act_Weight_3: "DB1,REAL32",
  sql_insert_Trigger: "DB1,X36.0",
  sql_insert_On: "DB1,X36.1",
  sql_insert_Off: "DB1,X36.2",
  sql_insert_Temp: "DB1,X36.3",
  sql_delete_Trigger: "DB1,X36.4",
  sql_OrderID: "DB1,S38.50",
  sql_Weight1_Setting: "DB1,REAL294",
  sql_Weight2_Setting: "DB1,REAL298",
  sql_Weight3_Setting: "DB1,REAL302",
  sql_Weight1_Actual: "DB1,REAL306",
  sql_Weight2_Actual: "DB1,REAL310",
  sql_Weight3_Actual: "DB1,REAL314",
  sql_Time_Tron_Setting: "DB1,INT318",
  sql_Time_Tron_Actual: "DB1,INT320",
  on_System: "DB1,X322.0",
  off_System: "DB1,X322.1",
  Alarm_M1: "DB4,X0.0",
  Alarm_M2: "DB4,X0.1",
  Alarm_M3: "DB4,X0.2",
  Alarm_Mix: "DB4,X0.3",
  Alarm_Export: "DB4,X0.4",
};
var tags_list_s2 = {
  btt_Auto_s2: "DB1,X0.0",
  btt_Manu_s2: "DB1,X0.1",
  btt_Auto_Confirm_s2: "DB1,X0.2",
  btt_V1_Open_s2: "DB1,X0.3",
  btt_V1_Close_s2: "DB1,X0.4",
  btt_V2_Open_s2: "DB1,X0.5",
  btt_V2_Close_s2: "DB1,X0.6",
  btt_V3_Open_s2: "DB1,X0.7",
  btt_V3_Close_s2: "DB1,X1.0",
  btt_DC_Tron_Run_s2: "DB1,X1.1",
  btt_DC_Tron_Stop_s2: "DB1,X1.2",
  btt_DC_Export_Run_s2: "DB1,X1.3",
  btt_DC_Export_Stop_s2: "DB1,X1.4",
  CB_Can_s2: "DB1,X1.5",
  Q_Lamp_Auto_s2: "DB1,X1.6",
  Q_Lamp_Manu_s2: "DB1,X1.7",
  status_Valve_1_s2: "DB1,BYTE2",
  status_Valve_2_s2: "DB1,BYTE3",
  status_Valve_3_s2: "DB1,BYTE4",
  status_DC_Tron_s2: "DB1,BYTE5",
  status_DC_Export_s2: "DB1,BYTE6",
  Setting_Time_Tron_s2: "DB1,INT8",
  Act_Time_Tron_s2: "DB1,INT10",
  Setting_Weight_1_s2: "DB1,REAL12",
  Setting_Weight_2_s2: "DB1,REAL16",
  Setting_Weight_3_s2: "DB1,REAL20",
  Act_Weight_1_s2: "DB1,REAL24",
  Act_Weight_2_s2: "DB1,REAL28",
  Act_Weight_3_s2: "DB1,REAL32",
  sql_insert_Trigger_s2: "DB1,X36.0",
  sql_insert_On_s2: "DB1,X36.1",
  sql_insert_Off_s2: "DB1,X36.2",
  sql_insert_Temp_s2: "DB1,X36.3",
  sql_delete_Trigger_s2: "DB1,X36.4",
  sql_OrderID_s2: "DB1,S38.50",
  sql_Weight1_Setting_s2: "DB1,REAL294",
  sql_Weight2_Setting_s2: "DB1,REAL298",
  sql_Weight3_Setting_s2: "DB1,REAL302",
  sql_Weight1_Actual_s2: "DB1,REAL306",
  sql_Weight2_Actual_s2: "DB1,REAL310",
  sql_Weight3_Actual_s2: "DB1,REAL314",
  sql_Time_Tron_Setting_s2: "DB1,INT318",
  sql_Time_Tron_Actual_s2: "DB1,INT320",
  on_System_s2: "DB1,X322.0",
  off_System_s2: "DB1,X322.1",
  Alarm_M1_s2: "DB4,X0.0",
  Alarm_M2_s2: "DB4,X0.1",
  Alarm_M3_s2: "DB4,X0.2",
  Alarm_Mix_s2: "DB4,X0.3",
  Alarm_Export_s2: "DB4,X0.4",
};

function PLC_connected(err) {
  if (typeof err !== "undefined") {
    console.log(err); // Hiển thị lỗi nếu không kết nối đƯỢc với PLC
  }
  conn_plc.setTranslationCB(function (tag) {
    return tags_list[tag];
  }); // Đưa giá trị đọc lên từ PLC và mảng
  conn_plc.addItems([
    "btt_Auto",
    "btt_Manu",
    "btt_Auto_Confirm",
    "btt_V1_Open",
    "btt_V1_Close",
    "btt_V2_Open",
    "btt_V2_Close",
    "btt_V3_Open",
    "btt_V3_Close",
    "btt_DC_Tron_Run",
    "btt_DC_Tron_Stop",
    "btt_DC_Export_Run",
    "btt_DC_Export_Stop",
    "CB_Can",
    "Q_Lamp_Auto",
    "Q_Lamp_Manu",
    "status_Valve_1",
    "status_Valve_2",
    "status_Valve_3",
    "status_DC_Tron",
    "status_DC_Export",
    "Setting_Time_Tron",
    "Act_Time_Tron",
    "Setting_Weight_1",
    "Setting_Weight_2",
    "Setting_Weight_3",
    "Act_Weight_1",
    "Act_Weight_2",
    "Act_Weight_3",
    "sql_insert_Trigger",
    "sql_insert_On",
    "sql_insert_Off",
    "sql_insert_Temp",
    "sql_delete_Trigger",
    "sql_OrderID",
    "sql_Weight1_Setting",
    "sql_Weight2_Setting",
    "sql_Weight3_Setting",
    "sql_Weight1_Actual",
    "sql_Weight2_Actual",
    "sql_Weight3_Actual",
    "sql_Time_Tron_Setting",
    "sql_Time_Tron_Actual",
    "on_System",
    "off_System",
    "Alarm_M1",
    "Alarm_M2",
    "Alarm_M3",
    "Alarm_Mix",
    "Alarm_Export",
  ]);
}
//PLC2
function PLC_connected_s2(err) {
  if (typeof err !== "undefined") {
    console.log(err); // Hiển thị lỗi nếu không kết nối đƯỢc với PLC
  }
  conn_plc_s2.setTranslationCB(function (tag) {
    return tags_list_s2[tag];
  }); // Đưa giá trị đọc lên từ PLC và mảng
  conn_plc_s2.addItems([
    "btt_Auto_s2",
    "btt_Manu_s2",
    "btt_Auto_Confirm_s2",
    "btt_V1_Open_s2",
    "btt_V1_Close_s2",
    "btt_V2_Open_s2",
    "btt_V2_Close_s2",
    "btt_V3_Open_s2",
    "btt_V3_Close_s2",
    "btt_DC_Tron_Run_s2",
    "btt_DC_Tron_Stop_s2",
    "btt_DC_Export_Run_s2",
    "btt_DC_Export_Stop_s2",
    "CB_Can_s2",
    "Q_Lamp_Auto_s2",
    "Q_Lamp_Manu_s2",
    "status_Valve_1_s2",
    "status_Valve_2_s2",
    "status_Valve_3_s2",
    "status_DC_Tron_s2",
    "status_DC_Export_s2",
    "Setting_Time_Tron_s2",
    "Act_Time_Tron_s2",
    "Setting_Weight_1_s2",
    "Setting_Weight_2_s2",
    "Setting_Weight_3_s2",
    "Act_Weight_1_s2",
    "Act_Weight_2_s2",
    "Act_Weight_3_s2",
    "sql_insert_Trigger_s2",
    "sql_insert_On_s2",
    "sql_insert_Off_s2",
    "sql_insert_Temp_s2",
    "sql_delete_Trigger_s2",
    "sql_OrderID_s2",
    "sql_Weight1_Setting_s2",
    "sql_Weight2_Setting_s2",
    "sql_Weight3_Setting_s2",
    "sql_Weight1_Actual_s2",
    "sql_Weight2_Actual_s2",
    "sql_Weight3_Actual_s2",
    "sql_Time_Tron_Setting_s2",
    "sql_Time_Tron_Actual_s2",
    "on_System_s2",
    "off_System_s2",
    "Alarm_M1_s2",
    "Alarm_M2_s2",
    "Alarm_M3_s2",
    "Alarm_Mix_s2",
    "Alarm_Export_s2",
  ]);
}

conn_plc.initiateConnection(
  {
    port: process.env.CPU_PORT,
    host: process.env.CPU_HOST_1,
    rack: process.env.CPU_RACK,
    slot: process.env.CPU_SLOT,
  },
  PLC_connected
);

conn_plc_s2.initiateConnection(
  {
    port: process.env.CPU_PORT,
    host: process.env.CPU_HOST_2,
    rack: process.env.CPU_RACK,
    slot: process.env.CPU_SLOT,
  },
  PLC_connected_s2
);

module.exports = {
  conn_plc,
  conn_plc_s2,
};
